paystack:
  initializeApi: https://api.paystack.co/transaction/initialize
  secretKey: ${PAYSTACK_SECRET_KEY}
  verifyApi: https://api.paystack.co/transaction/verify
  transactionApi: https://api.paystack.co/transaction
  chargeApi: https://api.paystack.co/charge
  otpApi: https://api.paystack.co/charge/submit_otp
  transferApi: https://api.paystack.co/transfer
  finalizeTransferApi: https://api.paystack.co/transfer/finalize_transfer
  customerApi: https://api.paystack.co/customer





spring:
  application:
    name: paystack
  profiles:
    active: dev

logging:
  level:
    root: DEBUG

server:
  port: 8080